---
AWSTemplateFormatVersion: '2010-09-09'
Description: server template

Parameters:
  Vpc:
    Default: vpc-c2701ca6
    Type: AWS::EC2::VPC::Id
  EC2Count:
    Default: 1
    Type: Number
  KeyPair:
    Default: ''
    Type: String
  Subnet0:
    Default: subnet-5e911e63
    Type: String
  Subnet1:
    Default: subnet-2ecc3a76
    Type: String
  Subnet2:
    Default: subnet-c39847b5
    Type: String
  Subnet3:
    Default: subnet-40e4076a
    Type: String
  InstanceType:
    Default: t2.micro
    Type: String
  PublicIPCidr:
    Default: 47.186.133.28/32
    Type: String
  EC2AMI:
    Default: ami-38de8d2f
    Type: AWS::EC2::Image::Id

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      Policies:
      - PolicyName: S3List
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:ListBucket
            Resource:
            - arn:aws:s3:::jaymell-ip-mapper
            - arn:aws:s3:::jaymell-camlistore-us-east-1
            Effect: Allow
      - PolicyName: S3Access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            Resource:
            - arn:aws:s3:::jaymell-ip-mapper/*
            - arn:aws:s3:::jaymell-camlistore-us-east-1/*
            Effect: Allow
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: InstanceRole

  InstanceSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: ServerSG
      GroupDescription: Server Security Group
      SecurityGroupIngress:
      - 
        ToPort: 22
        FromPort: 22
        IpProtocol: tcp
        CidrIp: 0.0.0.0/0
      - 
        ToPort: 8080
        FromPort: 8080
        IpProtocol: tcp
        CidrIp: !Ref PublicIPCidr

  LaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xv
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            apt-get update
            debconf-set-selections <<< 'mysql-server mysql-server/root_password password ""'
            debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password ""'
            apt-get install -y python2.7 git vim-common python-pip mongodb software-properties-common libssl-dev libffi-dev nodejs npm mysql-server
            pip install awscli ansible
            git clone https://github.com/jaymell/ansible-misc /tmp/ansible-misc
            su - ubuntu /bin/bash -c "cd /tmp/ansible-misc && ansible-playbook -i localhost /tmp/ansible-misc/playbooks/golang-download-localhost.yml --extra-vars=user_name=ubuntu"
            su - ubuntu /bin/bash -c "git clone https://github.com/jaymell/nodeSkel"
            su - ubuntu /bin/bash -c "cd /home/ubuntu/nodeSkel && npm i && aws s3 cp s3://jaymell-ip-mapper/nodeSkel/config.js ."
            cp /home/ubuntu/nodeSkel/nodeskel.service /etc/systemd/system/
            systemctl daemon-reload
            systemctl enable mongodb nodeskel
            systemctl start mongodb nodeskel
            su - ubuntu /bin/bash -c "export GOPATH=/home/ubuntu/go && go get github.com/jaymell/ip-mapper/... && go get github.com/jaymell/go-serve/..."
            ### download ip-mapper config files from s3
            ### install ip-mapper service file
            ### get latest backup of mongo database
      BlockDeviceMappings:
      - DeviceName: "/dev/xvda"
        Ebs:
          DeleteOnTermination: true
          VolumeType: gp2
          VolumeSize: 20
      KeyName:
        Ref: KeyPair
      SecurityGroups:
      - "Fn::GetAtt":
        - InstanceSG
        - GroupId
      IamInstanceProfile:
        Ref: InstanceProfile
      InstanceType:
        Ref: InstanceType
      AssociatePublicIpAddress: true
      ImageId:
        Ref: EC2AMI

  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize:
        Ref: EC2Count
      # Tags:
      MaxSize:
        Ref: EC2Count
      HealthCheckGracePeriod: '600'
      DesiredCapacity:
        Ref: EC2Count
      LaunchConfigurationName:
        Ref: LaunchConfig
      VPCZoneIdentifier:
      - Ref: Subnet0
      - Ref: Subnet1
      - Ref: Subnet2
      - Ref: Subnet3
      HealthCheckType: EC2
      Tags:
      - PropagateAtLaunch: 'true'
        Key: Name
        Value: server-ASG

      # AvailabilityZones:
      # - Fn::Select:
      #   - 0
      #   - Fn::GetAZs:
      #       Ref: AWS::Region
      # - Fn::Select:
      #   - 1
      #   - Fn::GetAZs:
      #       Ref: AWS::Region
#    CreationPolicy:
#      ResourceSignal:
#        Count:
#          Ref: EC2Count
#        Timeout: PT25M
